import {
    Moon,
    Sun,
    MessageSquare,
    Plus,
    ArrowLeft,
    Trash2,
    MoreVertical,
    Send,
    Paperclip,
    PlusCircle,
    Image as ImageIcon,
    Loader2,
    CheckCircle2,
    XCircle,
    Command,
    BookOpen,
    Clock,
    Laptop,
    User
 } from 'lucide-react';

export const Icons = {
    sun: Sun,
    moon: Moon,
    message: MessageSquare,
    plus: Plus,
    arrowLeft: ArrowLeft,
    trash: Trash2,
    moreVertical: MoreVertical,
    send: Send,
    paperclip: Paperclip,
    plusCircle: PlusCircle,
    image: ImageIcon,
    spinner: Loader2,
    checkCircle: CheckCircle2,
    xCircle: XCircle,
    logo: Command,
    bookOpen: BookOpen,
    clock: Clock,
    laptop: Laptop,
    user: User
};
