
import {
  LucideProps,
  Home,
  Users,
  Film,
  Bot,
  User,
  CloudSun,
  Map,
  Store,
  Landmark,
  Stethoscope,
  MessageSquare,
  LayoutDashboard,
  Settings,
  Plus,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Sun,
  Moon,
  Laptop,
  Twitter,
  Github,
  X,
  Loader2,
  MoreVertical,
  Trash,
  User2,
  Leaf,
  Tractor,
  Thermometer,
  Droplets,
  Wind,
  Shield,
  BadgeCheck,
  Wheat,
  Image as ImageIcon,
  Heart,
  MessageCircle,
  Share2,
  Bookmark,
  Send,
  Trophy,
  MapPin,
  Scaling,
  Sprout,
  BarChart
} from "lucide-react";

export const Icons = {
  home: Home,
  community: Users,
  reels: Film,
  ai: Bot,
  profile: User,
  weather: CloudSun,
  village: Map,
  market: Store,
  schemes: Landmark,
  aiDoctor: Stethoscope,
  messages: MessageSquare,
  dashboard: LayoutDashboard,
  settings: Settings,
  add: Plus,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  github: Github,
  close: X,
  spinner: Loader2,
  ellipsis: MoreVertical,
  trash: Trash,
  user: User2,
  logo: Leaf,
  tractor: Tractor,
  temperature: Thermometer,
  humidity: Droplets,
  wind: Wind,
  shield: Shield,
  verified: BadgeCheck,
  crop: Wheat,
  post: ImageIcon,
  like: Heart,
  comment: MessageCircle,
  share: Share2,
  bookmark: Bookmark,
  send: Send,
  leaderboard: Trophy,
  pin: MapPin,
  soil: Scaling,
  plant: Sprout,
  analytics: BarChart
};
